/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oxs.helper;

import java.util.Random;
import oxs.helper.Request;
import _global.tri.oxidationstates.webapi.PageData;
import _global.tri.oxidationstates.webapi.WebOxidationAnalyzer;

/**
 * Helper class to consume to consume oxidationstates library
 */
public class OxsHelper 
{
    /**
     * Default constructor.<p>
     */
    public OxsHelper()
    {
    }


    /**
     * Get a json string using the oxidation library
     */
    
    public String GetOxidationJSON(Request request)
    {   
        String paramFileName = "input_files/oxidation_boundaries.json";
        String polyIonDir = "input_files/polyatomic_ions_web";
        String result = "";
        
        if (!request.composition.isEmpty()) {
            WebOxidationAnalyzer analyzer = new WebOxidationAnalyzer(paramFileName, polyIonDir);
            PageData pageData = analyzer.getPageDataFromComposition(request.composition);
            result = pageData.toJSON();            
        } else if (!request.structure.isEmpty()) {
            WebOxidationAnalyzer analyzer = new WebOxidationAnalyzer(paramFileName, polyIonDir);
            PageData pageData = analyzer.getPageDataFromStructure(request.structure);
            result = pageData.toJSON();
        }
        return result;
    }
}// end of OxsHelper class