export interface FAQText {
    question: string;
    answer: string;
}

export const FAQs: FAQText[] = [
    {
        question: 'How can I cite the Oxidaiton State Analyzer?',
        answer: 'If you would like to cite the oxidation state analyzer, please reference the following manuscript: PLACEHOLDER. You can directly export this reference to a citation manager by clicking on one of the following links: PLACEHOLDER'
    },
    {
        question: 'For what species can oxidation states be calculated?',
        answer: 'Oxidation states can be calculated for all elements other than PLACEHOLDER, as well as the following polyatomic species: AsO<sub>4</sub>, BO<sub>3</sub>, C<sub>2</sub>O<sub>4</sub>, CIO<sub>4</sub>, CN, CO, CrO<sub>4</sub>, GeO<sub>4</sub>, MoO<sub>4</sub>, NO<sub>2</sub>, NO<sub>3</sub>, P<sub>2</sub>O<sub>7</sub>, PO<sub>3</sub>, PO<sub>4</sub>, PS<sub>4</sub>, SeO<sub>3</sub>, SeO<sub>4</sub>, SiO<sub>4</sub>, SO<sub>2</sub>, SO<sub>3</sub>, SO<sub>4</sub>, and WO<sub>4</sub>. Representative structures of these polyatomic ions can be downloaded here.'
    },
    {
        question: `Some possible combinations of oxidation states don't appear in the table. Why?`,
        answer: 'We have not generated parameters for rare oxidation states, defined here as states that do not appear in at least 25 materials in out data set. The table also only displays combinations of oxidation states with maximum likelihoods of at least 0.005. If no combination passes this threshold, the most likely combination is shown. A table including less likely combinations of oxidation states can be generated by downloading the library and directly calling its API. The Oxidation State Analyzer also currently only allows one species to have more than one oxidation state in a single material.'
    },
    {
        question: 'Some oxidation states appear in the table, but not in the colored bars on the right. Why?',
        answer: 'The fitted potential range for some oxidation states is too narrow to see in the plots on the right.'
    },
    {
        question: 'What are the units of the fitted potential (E)?',
        answer: 'The oxidation state analyzer is trained from a data set of labeled oxidation states of known materials, which contains no information about energies or electronic chemical potentials. To approximately map the boundaries for the oxidation state ranges to a physical scale, we have used linear least-squares regression to fit the boundary values to data from the electrochemical series.  (More details of this process are available in our manuscript). We use this fit to re-scale the boundary values to a “fitted potential” with units that approximate volts. All values are given relative to that of the boundary between H<sup>1-</sup> and H<sup>1+</sup>.'
    },
    {
        question: 'What is the likelihood score?',
        answer: 'The likelihood score represents the estimated likelihood that a particular combination of oxidation states coexists in a stable material at a given electronic chemical potential (or equivalently, at a given fitted potential).  More information is available in our manuscript.'
    },
    {
        question: 'What is the optimal potential?',
        answer: 'The optimal potential, E<sub>opt</sub>, is the fitted potential that maximizes the likelihood score.'
    },
    {
        question: 'What is the global instability index?',
        answer: `The <a rel='noopener noreferrer' target='_blank' href='https://doi.org/10.1016/0022-4596(92)90094-C'>global instability index</a> is the root-mean-squared difference between the oxidation states of each atom and the bond valence sum for that atom. The bond valence sum was calculated using the parameters published by <a rel='noopener noreferrer' target='_blank' href='https://doi.org/10.1107/S0108768190011041'>Brese and O'Keeffe</a>.`
    },
    {
        question: 'What file formats can I use to upload structures?',
        answer: 'We currently support the VASP POSCAR format and the Crystallographic Information Framework (CIF) format.'
    },
    {
        question: 'How are oxidation states assigned to sites in the structure?',
        answer: 'The oxidation states are assigned to sites in the unit cell of a structure in a way that minimizes the global instability index.  If multiple different assignments would result in nearly identical global instability indices, then a structure is generated with the average occupancies of all of these assignments. This can result in a structure with partially occupied sites.'
    },
    {
        question: 'Is the Oxidation State Analyzer available for offline use?',
        answer: 'The library used to evaluate oxidation states is open source and available for offline use. A description of this library, installation instructions, and API documentation can be found here.'
    },
    {
        question: 'Can I download all of the oxidation state ranges?',
        answer: 'The oxidation state ranges for all available species can be downloaded in JSON format here. The units are the same as those used on this web site.'
    }
];
