services:
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./docker.nginx.conf
        target: /etc/nginx/conf.d/default.conf

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 8000:8000