name: End-to-end tests
on:
  push:
    branches: [ "e2eTest" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
     #   working-directory: tests

    steps:
      - uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci
      - name: Start server in the background
        run: npm start & 
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          #start: npm start
          working-directory: tests