name: End-to-end tests
on:
  push:
    branches: [ "e2eTest" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: actions/setup-node@v3
        with:
          #node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: tests/package-lock.json

