name: End-to-end tests
on:
  push:
    branches: [ "e2eTest" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
     #   working-directory: tests

    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          #browser: chrome
          #start: npm start
          #record: true
          working-directory: tests