name: End-to-end tests
on:
  push:
    branches: [ "e2eTest" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    #container: 
    #  image: cypress/browsers:node18.12.0-chrome106-ff106
    #  options: --user 1001
    #defaults:
    #  run:
     #   working-directory: tests
    defaults:
      run:
        working-directory: tests

    strategy:
      matrix:
        node-version: [20.x]
        

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: tests/package-lock.json
      - uses: cypress-io/github-action@v5
        #with:
          #build : npm run build
          #start : npm start
          #browser: firefox
          #start: npm start
          #record: true
          #working-directory: tests
      - uses: actions/upload-artifact@v3
          # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v3
        with:
            name: cypress-videos
            path: cypress/videos
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  